site_name: 全民瘋AI系列 [深度學習與神經網路]
site_author: 10程式中
site_url: https://andy6804tw.github.io/crazyai-dl/
extra_css:
  - 'stylesheets/extra.css'
  - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
theme:
  name: material
  language: 'zh-TW'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'red'
    accent: 'red'
repo_url: https://github.com/andy6804tw/crazyai-dl
# use_directory_urls: false
edit_uri: ""
# Copyright
copyright: 'Copyright © 2023 - 2024 10程式中'
nav:
  - '1.基礎概念':
    - '1.基礎概念/1.1迴歸分析.md'
    - '1.基礎概念/1.2探索誤差的來源.md'
    - '1.基礎概念/1.3梯度下降的原理.md'
    - '1.基礎概念/1.4分類問題.md'
    - '1.基礎概念/1.5邏輯迴歸.md'

  - '2.深度神經網路':
    - '2.深度神經網路/2.1深度學習簡介.md'
    
  - '3. 卷積神經網路':
    - '3.卷積神經網路/3.1CNN.md'
    - '3.卷積神經網路/3.2ResNet.md'
  # - '4. 循環神經網路':
  - '5.Transformer架構':
    - '5.Transformer架構/5.1Attention Is All You Need.md'
    - '5.Transformer架構/5.2Transformer.md'
    - '5.Transformer架構/5.3Transformer.md'
  - 'TensorFlow 101 從零開始':
    - 'TensorFlow 101 從零開始/README.md'
    - 'TensorFlow 101 從零開始/TensorFlow 基礎介紹.md'
    - 'TensorFlow 101 從零開始/DNN Regression.md'
    - 'TensorFlow 101 從零開始/DNN Classification.md'
  - 'PyTorch 101':
    - 'PyTorch 101/1. PyTorch 基礎介紹.md'  

markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
plugins:
  - tags:
      tags_file: tags.md
  - search
#   - mkpdfs:
#       design: design/report.css
#       author: Tsai Yi Lin
#       # company: "10程式中"
#       toc_title: Table of contents
#       output_path: pdf/全民瘋AI系列_深度學習與神經網路_v1.0.pdf
